<div class="content-wrapper-form shadow">
    <h1>Register Form</h1>
    <p>Already registered? You can sign in <a href="loginProject/login">here</a>.</p>
    <form method="post" >
        <label for="email">Email: </label>
        <input placeholder="adam.pepega@seznam.cz" type="email" name="email" id="email">
        <label for="password">Password: </label>
        <div class="password-wrapper">
            <div class="pass-icon" onclick="passChange()">👀</div>
            <input type="password" name="password" id="password">
        </div>
        <label for="passwordRepeat">Password: </label>
        <div class="password-wrapper">
            <div class="pass-icon" onclick="passChange2()">👀</div>
            <input type="password" name="passwordRepeat" id="passwordRepeat">
        </div>
        <?php if ($_SESSION['errorMsg'][0]) echo "<div class='error-msg'>" . $_SESSION['errorMsg'][1] . "</div>" ?>
        <input class="btn btn-hover title-2" type="submit" value="Submit">
    </form>
</div>
<script>
    const input = document.querySelector('#password');
    const input2 = document.querySelector('#passwordRepeat');

    const passChange = () => {
        if (input.type === 'password') {
            input.type = 'text';
        } else {
            input.type = 'password';
        }
    }
    const passChange2 = () => {
        if (input2.type === 'password') {
            input2.type = 'text';
        } else {
            input2.type = 'password';
        }
    }
</script>
